version: '3.8'

services:
  restapi:
    build: .
    depends_on:
      - "db"
      - "rabbitmq"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=postgres"
    ports:
      - "8081:8081"
    networks:
      - paperless-network

  webserver:
    build:
      context: ../Paperless_ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - paperless-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - paperless-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Port for RabbitMQ broker
      - "15672:15672"  # Port for RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - paperless-network

volumes:
  pgdata: {}

networks:
  paperless-network:
    driver: bridge
